inherit_from:
  - https://raw.githubusercontent.com/alcesleo/rubocop-config/master/.rubocop.yml

### Disabled

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "apps/web/application.rb"

Style/BlockDelimiters:
  Exclude:
    - "spec/support/factories.rb"
